"""FISMA self-audit orchestration (FR-FISMAAUDIT-6/7/9/10).

Runs every check in the registry, aggregates outcomes, and persists one
FismaAuditReport row with full findings + history. Advisory-only
(FR-FISMAAUDIT-9): this module NEVER mutates any control's configuration —
it only reports.
"""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.audit.decorator import audited
from app.compliance.fisma_audit.checks import REGISTRY
from app.compliance.fisma_audit.models import FismaAuditReport
from app.config import get_settings
from app.logging import get_logger

log = get_logger("compliance.fisma_audit")

# FR-FISMAAUDIT-10: standing self-assessment disclaimer, carried forward
# from docs/SECURITY-SELF-AUDIT.md's own header language.
DISCLAIMER = (
    "This is a self-assessment generated by the chassis's own runtime checks. "
    "It is not an independent audit or an Authority to Operate."
)


@audited("fisma_audit.run", entity_type="fisma_audit_report")
async def run_audit(
    session: AsyncSession, *, triggered_by_user_id: int | None = None
) -> FismaAuditReport:
    """Run every registered check and persist the resulting report."""
    settings = get_settings()
    findings: list[dict[str, str]] = []
    pass_count = fail_count = na_count = operator_count = 0

    for check in REGISTRY:
        try:
            outcome, detail = await check.fn(session)
        except Exception as exc:  # noqa: BLE001 — a broken check is a finding, not a crash
            log.warning("fisma_audit.check_raised", control_id=check.control_id, error=str(exc))
            outcome, detail = "check_error", f"check raised: {exc}"

        findings.append(
            {
                "control_id": check.control_id,
                "title": check.title,
                "outcome": outcome,
                "detail": detail,
            }
        )
        if outcome == "pass":
            pass_count += 1
        elif outcome in ("fail", "check_error"):
            fail_count += 1
        elif outcome == "not_applicable":
            na_count += 1
        elif outcome == "operator_responsibility":
            operator_count += 1

    report = FismaAuditReport(
        fisma_level=settings.fisma_level,
        findings=findings,
        pass_count=pass_count,
        fail_count=fail_count,
        not_applicable_count=na_count,
        operator_responsibility_count=operator_count,
        triggered_by_user_id=triggered_by_user_id,
    )
    session.add(report)
    await session.flush()
    return report


async def get_latest_report(session: AsyncSession) -> FismaAuditReport | None:
    stmt = select(FismaAuditReport).order_by(FismaAuditReport.ran_at.desc()).limit(1)
    return (await session.execute(stmt)).scalar_one_or_none()


async def list_report_history(session: AsyncSession, *, limit: int = 20) -> list[FismaAuditReport]:
    stmt = select(FismaAuditReport).order_by(FismaAuditReport.ran_at.desc()).limit(limit)
    return list((await session.execute(stmt)).scalars().all())
