"""accessibility_assistant slot: tables for the generated accessibility_assistant slot

Revision ID: 0015
Revises: 0014

Generated by the App Builder (AB-FR-631). The upgrade/downgrade bodies below
are the slot's own; this header is written by the platform so the revision
chains onto the real head of migrations/versions/.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


"""Accessibility Assistant slot — Alembic migration body.

upgrade() creates the three slot tables:
  - aa_question_categories
  - aa_faqs
  - aa_interaction_logs

downgrade() drops them in reverse dependency order.

Columns match models.py exactly. The `op` and `sa` names are injected
by the Alembic migration runner — do not import them here.
"""


def upgrade() -> None:
    # aa_question_categories
    op.create_table(
        "aa_question_categories",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "org_id",
            sa.Integer(),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("org_id", "name", name="uq_aa_qcat_org_name"),
    )
    op.create_index(
        "ix_aa_question_categories_org_id",
        "aa_question_categories",
        ["org_id"],
    )

    # aa_faqs
    op.create_table(
        "aa_faqs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "org_id",
            sa.Integer(),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "question_category_id",
            sa.Integer(),
            sa.ForeignKey("aa_question_categories.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False, server_default=""),
        sa.Column("reasoning", sa.Text(), nullable=False, server_default=""),
        sa.Column("citations_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_aa_faqs_org_id", "aa_faqs", ["org_id"])
    op.create_index(
        "ix_aa_faqs_question_category_id",
        "aa_faqs",
        ["question_category_id"],
    )

    # aa_interaction_logs
    op.create_table(
        "aa_interaction_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "org_id",
            sa.Integer(),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "question_category_id",
            sa.Integer(),
            sa.ForeignKey("aa_question_categories.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("reasoning", sa.Text(), nullable=False, server_default=""),
        sa.Column("sources_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("rating", sa.Boolean(), nullable=True),
        sa.Column(
            "retained_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment=(
                "SI-12: row expires after this timestamp; archival jobs use "
                "this column to select rows for offline archival. NULL = no "
                "scheduled expiration (subject to chassis-wide AU-11 only)."
            ),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_aa_interaction_logs_org_id", "aa_interaction_logs", ["org_id"]
    )
    op.create_index(
        "ix_aa_interaction_logs_user_id", "aa_interaction_logs", ["user_id"]
    )
    op.create_index(
        "ix_aa_interaction_logs_question_category_id",
        "aa_interaction_logs",
        ["question_category_id"],
    )
    op.create_index(
        "ix_aa_interaction_logs_session_id",
        "aa_interaction_logs",
        ["session_id"],
    )
    op.create_index(
        "ix_aa_interaction_logs_created_at",
        "aa_interaction_logs",
        ["created_at"],
    )
    op.create_index(
        "ix_aa_interaction_logs_retained_until",
        "aa_interaction_logs",
        ["retained_until"],
    )


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_index(
        "ix_aa_interaction_logs_retained_until",
        table_name="aa_interaction_logs",
    )
    op.drop_index(
        "ix_aa_interaction_logs_created_at",
        table_name="aa_interaction_logs",
    )
    op.drop_index(
        "ix_aa_interaction_logs_session_id",
        table_name="aa_interaction_logs",
    )
    op.drop_index(
        "ix_aa_interaction_logs_question_category_id",
        table_name="aa_interaction_logs",
    )
    op.drop_index(
        "ix_aa_interaction_logs_user_id",
        table_name="aa_interaction_logs",
    )
    op.drop_index(
        "ix_aa_interaction_logs_org_id",
        table_name="aa_interaction_logs",
    )
    op.drop_table("aa_interaction_logs")

    op.drop_index(
        "ix_aa_faqs_question_category_id",
        table_name="aa_faqs",
    )
    op.drop_index("ix_aa_faqs_org_id", table_name="aa_faqs")
    op.drop_table("aa_faqs")

    op.drop_index(
        "ix_aa_question_categories_org_id",
        table_name="aa_question_categories",
    )
    op.drop_table("aa_question_categories")
